config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resource :shop
    get 'count', to: 'users#user_count', on: :collection, defaults: { format: 'json' }
    get 'name', to: 'users#user_name', on: :member, defaults: { format: 'json' }
  end
end

app/models/shop.rb
class Shop
  include Mongoid::Document
  field :shop_name, type: String

  # reloations
  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  field :first_name, type: String
  field :last_name, type: String
  field :gender, type: String
  field :age, type: Integer
  field :address, type: Hash

  # relations
  has_one :shop

  # validations
  validates_presence_of :first_name, :last_name
  validates_inclusion_of :gender, in: %w(male female others)
  validates_inclusion_of :age, in: 1..99

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_user
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @shop = @user.build_shop
  end

  def edit
  end

  def create
    @shop = @user.build_shop(shop_params)
    respond_to do |format|
      if @shop.save
        format.html { redirect_to user_shop_url(@user), notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: user_shop_url(@user) }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to user_shop_url(@user), notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: user_shop_url(@user) }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to user_shop_url(@user), notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_shop
    @shop = @user.shop
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def shop_params
    params.require(:shop).permit(:shop_name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :user_name]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    address_keys = %w(country address_1 address_2)
    params.require(:user).permit(:last_name,
                                 :first_name,
                                 :age,
                                 :gender,
                                 address: address_keys)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnboardingTask</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div ng-app="onboardapp">
    <div class="container-fluid">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/shops/_form.html.erb
<%= form_for @shop, url: user_shop_path(@user) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shop_name %><br>
    <%= f.text_field :shop_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Edit shop</h1>

<%= render 'form' %>

<%= link_to 'Back', user_shop_path(@user) %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', user_shop_path(@user) %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>
<% if @shop %>
  <p>
    <strong>Shop name:</strong>
    <%= @shop.shop_name %>
    <%= link_to 'Edit', edit_user_shop_path(@user) %> |
    <%= link_to 'Destroy', user_shop_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </p>
<% else %>
  <h1><%= @user.full_name %>do not have shop right now.</h1>
  <%= link_to 'new', new_user_shop_path(@user) %>
<% end %>
<%= link_to 'Back', users_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :address_1 %><br>
    <%= f.text_field :address_1 %>
  </div>
  <div class="field">
    <%= f.label :address_2 %><br>
    <%= f.text_field :address_2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div ng-controller="UserEditController" ng-init="init('<%= @user.id %>')">
  <h1>Edit User</h1>
  <user-form></user-form>
</div>

app/views/users/index.html.erb
<div ng-controller="UserIndexController">
  <p id="notice"><%= notice %></p>

  <h1>Listing Users</h1>
  <h5>(total user: <strong id="user-count"> {{ users.length }}</strong>)</h5>

  <table>
    <thead>
      <tr>
        <th>Last name</th>
        <th>First name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <tr ng-repeat="user in users track by user.id.$oid">
        <td class="last_name">{{ user.last_name }}</td>
        <td class="first_name">{{ user.first_name }}</td>
        <td> <%= link_to 'show','#','ng-href' => "#{users_path()}/{{user.id.$oid}}" %>
        <td><button ng-click="openEditUserForm(user)">Edit</button></td>
        <td><button confirm-click="deleteUser(user.id.$oid)" confirm-alert-message="Are you sure?">Destroy</button></td>
        <td> <%= link_to 'shop','#','ng-href' => "#{users_path()}/{{user.id.$oid}}/shop" %>
        </td>
      </tr>
    </tbody>
  </table>

  <br>
  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
 <user-form></user-form>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <div id="last_name"><%= @user.last_name %></div>
</p>

<p>
  <strong>First name:</strong>
  <div id="first_name"><%= @user.first_name %></div>
</p>

<p>
  <strong>address:</strong>
  <div id="address_country"><%= @user.address[:country] %></div>
</p>

<p>
  <strong>First name:</strong>
  <div id="address_address_1"><%= @user.address[:address_1] %></div>
</p>

<p>
  <strong>First name:</strong>
  <div id="address_address_2"><%= @user.address[:address_2] %></div>
</p>

<%= link_to 'Back', users_path %>